### ISSUE TITLE
stestr shell help doesn't work

### ISSUE THREAD

**Issue by mtreinish** [mtreinish/stestr#144]
When running the stestr shell (by just running ``stestr`` with no commands) the help command doesn't work for any of the commands. For example:

```
(stestr) help failing
Traceback (most recent call last):
  File "/home/computertreker/.venvs/venv2/lib/python2.7/site-packages/cmd2.py", line 786, in onecmd_plus_hooks
    stop = self.onecmd(statement)
  File "/home/computertreker/.venvs/venv2/lib/python2.7/site-packages/cmd2.py", line 974, in onecmd
    stop = func(statement)
  File "/home/computertreker/.venvs/venv2/lib/python2.7/site-packages/cliff/interactive.py", line 114, in do_help
    self.default(self.parsed('help ' + arg))
AttributeError: InteractiveApp instance has no attribute 'parsed'
EXCEPTION of type 'AttributeError' occurred with message: 'InteractiveApp instance has no attribute 'parsed''
To enable full traceback, run the following command:  'set debug true
```

**Comment by masayukig** [comment]
This seems like cliff's issue..

```
$ cliffdemo
(cliffdemo) set debug true
debug - was: False
now: True
(cliffdemo) help file
Traceback (most recent call last):
  File "/home/masayuki/git/openstack/cliff/.tox/py36/lib/python3.6/site-packages/cmd2.py", line 787, in onecmd_plus_hooks
    stop = self.onecmd(statement)
  File "/home/masayuki/git/openstack/cliff/.tox/py36/lib/python3.6/site-packages/cmd2.py", line 975, in onecmd
    stop = func(statement)
  File "/home/masayuki/git/openstack/cliff/.tox/py36/lib/python3.6/site-packages/cliff/interactive.py", line 114, in do_help
    self.default('help ' + arg)
  File "/home/masayuki/git/openstack/cliff/.tox/py36/lib/python3.6/site-packages/cliff/interactive.py", line 60, in default
    line_parts = shlex.split(line.parsed.raw)
AttributeError: 'str' object has no attribute 'parsed'
EXCEPTION of type 'AttributeError' occurred with message: ''str' object has no attribute 'parsed''
To enable full traceback, run the following command:  'set debug true'
```

**Comment by masayukig** [comment]
Now, this works on python2.7 but not on 3.7.. :(
```
$ python --version
Python 2.7.16
(stestr) help failing
usage: failing [-h] [--subunit] [--list]

Show the current failures known by the repository. Without --subunit, the
<snip>
```

```
$ python --version
Python 3.7.3
$ stestr
(stestr) set debug true
debug - was: False
now: True
(stestr) help failing
Traceback (most recent call last):
  File "/home/masayuki/git/stestr/.tox/py37/lib/python3.7/site-packages/cmd2/cmd2.py", line 1750, in onecmd_plus_hooks
    statement = self.precmd(statement)
  File "/home/masayuki/git/stestr/.tox/py37/lib/python3.7/site-packages/cliff/interactive.py", line 172, in precmd
    statement.command = cmd_name
  File "/home/masayuki/git/stestr/.tox/py37/lib/python3.7/site-packages/attr/_make.py", line 428, in _frozen_setattrs
    raise FrozenInstanceError()
attr.exceptions.FrozenInstanceError
EXCEPTION of type 'FrozenInstanceError' occurred with message: ''
```
